import { Amaranth } from "next/font/google";
import "./globals.css";
import Navber from "./components/Navber";
import { AuthProvider } from "@/context/contextApi";
import { ToastContainer, Bounce } from "react-toastify";

const amaranth = Amaranth({
  weight: ["400", "700"],
  subsets: ["latin"],
});

export const metadata = {
  title: "Keen Keeper",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      data-theme="light"
      lang="en"
      className={` h-full bg-mainBg antialiased`}
    >
      <body className={amaranth.className}>
        <AuthProvider>
          <Navber />
          {children}
          <ToastContainer
            position="top-right"
            autoClose={5000}
            hideProgressBar={false}
            newestOnTop={false}
            closeOnClick={false}
            rtl={false}
            pauseOnFocusLoss
            draggable
            pauseOnHover
            theme="light"
            transition={Bounce}
          />
        </AuthProvider>
      </body>
    </html>
  );
}
