import { Amaranth, Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navber from "./components/Navber";
import { AuthProvider } from "@/context/contextApi";

const amaranth = Amaranth({
  weight: ["400", "700"],
  subsets: ["latin"],
});

export const metadata = {
  title: "Keen Keeper",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      data-theme="light"
      lang="en"
      className={` h-full bg-mainBg antialiased`}
    >
      <body className={amaranth.className}>
        <AuthProvider>
          <Navber />
          {children}
        </AuthProvider>
      </body>
    </html>
  );
}
